
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(908, 488)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 911, 491))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.04, y1:0.0449545, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(43, 255, 30, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(170, 10, 671, 41))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 150, 281, 201))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.kamera = QtWidgets.QLabel(self.groupBox)
        self.kamera.setGeometry(QtCore.QRect(10, 20, 261, 171))
        self.kamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kamera.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kamera.setLineWidth(3)
        self.kamera.setMidLineWidth(3)
        self.kamera.setText("")
        self.kamera.setObjectName("kamera")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(400, 40, 181, 41))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(360, 70, 231, 41))
        self.label_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 150, 281, 201))
        self.groupBox_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.capture = QtWidgets.QLabel(self.groupBox_2)
        self.capture.setGeometry(QtCore.QRect(10, 20, 261, 171))
        self.capture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.capture.setText("")
        self.capture.setObjectName("capture")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setGeometry(QtCore.QRect(600, 150, 281, 201))
        self.groupBox_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.hasil = QtWidgets.QLabel(self.groupBox_4)
        self.hasil.setGeometry(QtCore.QRect(10, 20, 261, 171))
        self.hasil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hasil.setText("")
        self.hasil.setObjectName("hasil")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 370, 371, 101))
        self.groupBox_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.Start_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.Start_pushButton.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.Start_pushButton.setStyleSheet("color: rgb(0, 0, 255);")
        self.Start_pushButton.setObjectName("Start_pushButton")
        self.Capture_pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Capture_pushButton_2.setGeometry(QtCore.QRect(130, 20, 111, 31))
        self.Capture_pushButton_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.Capture_pushButton_2.setObjectName("Capture_pushButton_2")
        self.Save_pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.Save_pushButton_3.setGeometry(QtCore.QRect(250, 20, 111, 31))
        self.Save_pushButton_3.setStyleSheet("color: rgb(0, 0, 255);")
        self.Save_pushButton_3.setObjectName("Save_pushButton_3")
        self.Proses_pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.Proses_pushButton_4.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.Proses_pushButton_4.setStyleSheet("color: rgb(0, 0, 255);")
        self.Proses_pushButton_4.setObjectName("Proses_pushButton_4")
        self.Exit_pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.Exit_pushButton_5.setGeometry(QtCore.QRect(130, 60, 111, 31))
        self.Exit_pushButton_5.setStyleSheet("color: rgb(0, 0, 255);")
        self.Exit_pushButton_5.setObjectName("Exit_pushButton_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(260, 100, 371, 101))
        self.groupBox_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.Start_pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.Start_pushButton_2.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.Start_pushButton_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.Start_pushButton_2.setObjectName("Start_pushButton_2")
        self.Capture_pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Capture_pushButton_3.setGeometry(QtCore.QRect(130, 20, 111, 31))
        self.Capture_pushButton_3.setStyleSheet("color: rgb(0, 0, 255);")
        self.Capture_pushButton_3.setObjectName("Capture_pushButton_3")
        self.Save_pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.Save_pushButton_4.setGeometry(QtCore.QRect(250, 20, 111, 31))
        self.Save_pushButton_4.setStyleSheet("color: rgb(0, 0, 255);")
        self.Save_pushButton_4.setObjectName("Save_pushButton_4")
        self.Proses_pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.Proses_pushButton_5.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.Proses_pushButton_5.setStyleSheet("color: rgb(0, 0, 255);")
        self.Proses_pushButton_5.setObjectName("Proses_pushButton_5")
        self.Exit_pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.Exit_pushButton_6.setGeometry(QtCore.QRect(130, 60, 111, 31))
        self.Exit_pushButton_6.setStyleSheet("color: rgb(0, 0, 255);")
        self.Exit_pushButton_6.setObjectName("Exit_pushButton_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setGeometry(QtCore.QRect(410, 370, 461, 101))
        self.groupBox_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(260, 100, 371, 101))
        self.groupBox_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.Start_pushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.Start_pushButton_4.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.Start_pushButton_4.setStyleSheet("color: rgb(0, 0, 255);")
        self.Start_pushButton_4.setObjectName("Start_pushButton_4")
        self.Capture_pushButton_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.Capture_pushButton_5.setGeometry(QtCore.QRect(130, 20, 111, 31))
        self.Capture_pushButton_5.setStyleSheet("color: rgb(0, 0, 255);")
        self.Capture_pushButton_5.setObjectName("Capture_pushButton_5")
        self.Save_pushButton_6 = QtWidgets.QPushButton(self.groupBox_7)
        self.Save_pushButton_6.setGeometry(QtCore.QRect(250, 20, 111, 31))
        self.Save_pushButton_6.setStyleSheet("color: rgb(0, 0, 255);")
        self.Save_pushButton_6.setObjectName("Save_pushButton_6")
        self.Proses_pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.Proses_pushButton_7.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.Proses_pushButton_7.setStyleSheet("color: rgb(0, 0, 255);")
        self.Proses_pushButton_7.setObjectName("Proses_pushButton_7")
        self.Exit_pushButton_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.Exit_pushButton_8.setGeometry(QtCore.QRect(130, 60, 111, 31))
        self.Exit_pushButton_8.setStyleSheet("color: rgb(0, 0, 255);")
        self.Exit_pushButton_8.setObjectName("Exit_pushButton_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 261, 16))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 241, 41))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 251, 31))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(250, 20, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 50, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 80, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(360, 70, 41, 31))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\">Jurusan Fisika</p><p align=\"center\">Universitas Lampung</p></body></html>"))
        self.label.setText(_translate("Dialog", "Deteksi Kematangan Nanas dengan Metode Thresholding "))
        self.groupBox.setTitle(_translate("Dialog", "Camera"))
        self.label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\">Jurusan Fisika</p><p align=\"center\">Universitas Lampung</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Jurusan Fisika"))
        self.label_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\">Jurusan Fisika</p><p align=\"center\">Universitas Lampung</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Universitas Lampung"))
        self.groupBox_2.setTitle(_translate("Dialog", "Capture"))
        self.groupBox_4.setTitle(_translate("Dialog", "Hasil"))
        self.groupBox_3.setTitle(_translate("Dialog", "Kontrol"))
        self.Start_pushButton.setText(_translate("Dialog", "Start"))
        self.Capture_pushButton_2.setText(_translate("Dialog", "Capture"))
        self.Save_pushButton_3.setText(_translate("Dialog", "Save"))
        self.Proses_pushButton_4.setText(_translate("Dialog", "Proses"))
        self.Exit_pushButton_5.setText(_translate("Dialog", "Exit"))
        self.groupBox_5.setTitle(_translate("Dialog", "Kontrol"))
        self.Start_pushButton_2.setText(_translate("Dialog", "Start"))
        self.Capture_pushButton_3.setText(_translate("Dialog", "Capture"))
        self.Save_pushButton_4.setText(_translate("Dialog", "Save"))
        self.Proses_pushButton_5.setText(_translate("Dialog", "Proses"))
        self.Exit_pushButton_6.setText(_translate("Dialog", "Exit"))
        self.groupBox_6.setTitle(_translate("Dialog", "Hasil"))
        self.groupBox_7.setTitle(_translate("Dialog", "Kontrol"))
        self.Start_pushButton_4.setText(_translate("Dialog", "Start"))
        self.Capture_pushButton_5.setText(_translate("Dialog", "Capture"))
        self.Save_pushButton_6.setText(_translate("Dialog", "Save"))
        self.Proses_pushButton_7.setText(_translate("Dialog", "Proses"))
        self.Exit_pushButton_8.setText(_translate("Dialog", "Exit"))
        self.label_4.setText(_translate("Dialog", "Jumlah Seluruh Mata Nanas       :"))
        self.label_5.setText(_translate("Dialog", "Jumlah Mata Nanas Kuning        :"))
        self.label_6.setText(_translate("Dialog", "Persentase Kematangan Nanas   :"))
        self.label_7.setText(_translate("Dialog", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
